image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: 
    - gradle build

jar:
  stage: deploy
  only:
    - master
  script:
    - gradle jar
  artifacts:
    paths:
    - build/libs/*.jar